In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import torch

In [5]:
x = torch.ones(5)
y = torch.zeros(3)
w = torch.randn(5,3,requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x,w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z,y)

In [7]:
z.grad_fn, loss.grad_fn

(<AddBackward0 at 0x7fc2129d08e0>,
 <BinaryCrossEntropyWithLogitsBackward0 at 0x7fc2128652d0>)

In [9]:
loss.backward(), w.grad, b.grad

(None,
 tensor([[0.3319, 0.3121, 0.1788],
         [0.3319, 0.3121, 0.1788],
         [0.3319, 0.3121, 0.1788],
         [0.3319, 0.3121, 0.1788],
         [0.3319, 0.3121, 0.1788]]),
 tensor([0.3319, 0.3121, 0.1788]))

In [10]:
# to freeze parameters, detach tracking
z_det = z.detach()
print(z_det.requires_grad)

False


In [20]:
# in case the loss function is also a vector, torch calculates the jacobian product given by vT.J, where v is the same size as the original tensor
input = torch.eye(4,5, requires_grad=True)
output = (input+1).pow(2).t()
output.backward(torch.ones_like(output), retain_graph=True)
output.backward(torch.ones_like(output), retain_graph=True)
input.grad.zero_()
output.backward(torch.ones_like(output), retain_graph=True)
input, output, input.grad

(tensor([[1., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0.],
         [0., 0., 1., 0., 0.],
         [0., 0., 0., 1., 0.]], requires_grad=True),
 tensor([[4., 1., 1., 1.],
         [1., 4., 1., 1.],
         [1., 1., 4., 1.],
         [1., 1., 1., 4.],
         [1., 1., 1., 1.]], grad_fn=<TBackward0>),
 tensor([[4., 2., 2., 2., 2.],
         [2., 4., 2., 2., 2.],
         [2., 2., 4., 2., 2.],
         [2., 2., 2., 4., 2.]]))

To understand this properly, read https://pytorch.org/docs/stable/notes/autograd.html 