In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np

In [3]:
# creating tensors directly
data = np.random.random((100,100))
x_data = torch.tensor(data)
x_data

tensor([[0.7598, 0.4631, 0.1341,  ..., 0.0470, 0.8023, 0.6352],
        [0.3156, 0.4405, 0.0802,  ..., 0.2267, 0.6748, 0.9082],
        [0.4126, 0.3887, 0.2969,  ..., 0.0794, 0.3039, 0.5560],
        ...,
        [0.7992, 0.9384, 0.8660,  ..., 0.8076, 0.5519, 0.5746],
        [0.6467, 0.9032, 0.3929,  ..., 0.8716, 0.4488, 0.2312],
        [0.7890, 0.6051, 0.0055,  ..., 0.2346, 0.1194, 0.1913]],
       dtype=torch.float64)

In [4]:
# creating tensors from numpy arrays 
x_np = torch.from_numpy(data)
x_np

tensor([[0.7598, 0.4631, 0.1341,  ..., 0.0470, 0.8023, 0.6352],
        [0.3156, 0.4405, 0.0802,  ..., 0.2267, 0.6748, 0.9082],
        [0.4126, 0.3887, 0.2969,  ..., 0.0794, 0.3039, 0.5560],
        ...,
        [0.7992, 0.9384, 0.8660,  ..., 0.8076, 0.5519, 0.5746],
        [0.6467, 0.9032, 0.3929,  ..., 0.8716, 0.4488, 0.2312],
        [0.7890, 0.6051, 0.0055,  ..., 0.2346, 0.1194, 0.1913]],
       dtype=torch.float64)

In [5]:
# creating tensors from other tensors
x_ones = torch.ones_like(x_np)
x_rand = torch.rand_like(x_data)
x_ones, x_rand

(tensor([[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]], dtype=torch.float64),
 tensor([[0.5976, 0.8977, 0.4748,  ..., 0.7581, 0.0924, 0.9813],
         [0.4373, 0.4155, 0.8838,  ..., 0.3931, 0.7274, 0.9537],
         [0.0933, 0.9434, 0.3893,  ..., 0.1129, 0.9062, 0.0154],
         ...,
         [0.5394, 0.5676, 0.9891,  ..., 0.4391, 0.6730, 0.6702],
         [0.1469, 0.5472, 0.7944,  ..., 0.8305, 0.2899, 0.8590],
         [0.9799, 0.6846, 0.9245,  ..., 0.3669, 0.4949, 0.7953]],
        dtype=torch.float64))

In [6]:
# creating tensors with a shape 
shape = (10,10)
s_ones = torch.ones(shape)
s_rand = torch.rand(shape)
s_zeros = torch.zeros(shape)
s_ones, s_zeros, s_rand

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.,

In [7]:
# tensor attributes
s_rand.shape, s_zeros.dtype, s_ones.device

(torch.Size([10, 10]), torch.float32, device(type='cpu'))

In [10]:
# tensor device to gpu
if torch.cuda.is_available(): s_rand = s_rand.to("cuda")
s_rand.shape, s_rand.dtype, s_rand.device

(torch.Size([10, 10]), torch.float32, device(type='cuda', index=0))

In [16]:
# tensor device back to cpu
s_rand = s_rand.to("cpu")
s_rand.shape, s_rand.dtype, s_rand.device

(torch.Size([10, 10]), torch.float32, device(type='cpu'))

In [19]:
# slicing and concatenation
s_rand[:2,:5], torch.cat([s_rand[:2,:5], s_ones[:2,:5]], dim=0)

(tensor([[0.9646, 0.7188, 0.0114, 0.8052, 0.6991],
         [0.6651, 0.4709, 0.2581, 0.6711, 0.6429]]),
 tensor([[0.9646, 0.7188, 0.0114, 0.8052, 0.6991],
         [0.6651, 0.4709, 0.2581, 0.6711, 0.6429],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
         [1.0000, 1.0000, 1.0000, 1.0000, 1.0000]]))

In [27]:
# arithematic
m1 = torch.rand([4,4])
m2 = torch.rand([4,4])
m1, m2

(tensor([[0.3639, 0.8726, 0.8560, 0.0504],
         [0.4933, 0.1323, 0.0922, 0.0533],
         [0.0238, 0.7172, 0.2330, 0.2553],
         [0.7679, 0.0150, 0.5543, 0.9658]]),
 tensor([[0.4407, 0.3502, 0.3829, 0.2488],
         [0.1027, 0.4773, 0.4417, 0.6903],
         [0.0106, 0.1724, 0.1151, 0.7032],
         [0.5643, 0.7614, 0.9561, 0.9252]]))

In [28]:
# element wise multiplication
m1*m2

tensor([[1.6035e-01, 3.0562e-01, 3.2776e-01, 1.2531e-02],
        [5.0661e-02, 6.3121e-02, 4.0726e-02, 3.6822e-02],
        [2.5176e-04, 1.2362e-01, 2.6815e-02, 1.7953e-01],
        [4.3334e-01, 1.1394e-02, 5.3002e-01, 8.9352e-01]])

In [31]:
torch.mul(m1, m2)

tensor([[1.6035e-01, 3.0562e-01, 3.2776e-01, 1.2531e-02],
        [5.0661e-02, 6.3121e-02, 4.0726e-02, 3.6822e-02],
        [2.5176e-04, 1.2362e-01, 2.6815e-02, 1.7953e-01],
        [4.3334e-01, 1.1394e-02, 5.3002e-01, 8.9352e-01]])

In [29]:
# matrix multiplication
m1 @ m2

tensor([[0.2874, 0.7298, 0.6714, 1.3414],
        [0.2620, 0.2924, 0.3089, 0.3282],
        [0.2307, 0.5852, 0.5968, 0.9011],
        [0.8908, 1.1070, 1.2879, 1.4847]])

In [30]:
# matrix multiplication
torch.matmul(m1, m2)

tensor([[0.2874, 0.7298, 0.6714, 1.3414],
        [0.2620, 0.2924, 0.3089, 0.3282],
        [0.2307, 0.5852, 0.5968, 0.9011],
        [0.8908, 1.1070, 1.2879, 1.4847]])

In [34]:
# converting to numerical value for single value tensor
m1.sum().item()

6.4463982582092285

In [35]:
# transpose a tensor
m1.T

tensor([[0.3639, 0.4933, 0.0238, 0.7679],
        [0.8726, 0.1323, 0.7172, 0.0150],
        [0.8560, 0.0922, 0.2330, 0.5543],
        [0.0504, 0.0533, 0.2553, 0.9658]])

In [41]:
# Tensor to Numpy array when using tensor.numpy() function but not np.array() function
np1 = m2.numpy()
np1

array([[0.44067085, 0.35023057, 0.38291526, 0.24875557],
       [0.10269308, 0.47726107, 0.44166583, 0.690346  ],
       [0.01055652, 0.17235869, 0.11507291, 0.7031706 ],
       [0.5642895 , 0.76141506, 0.9561253 , 0.92516685]], dtype=float32)

In [49]:
np2 = np.array(m2)
np2

array([[2.440671 , 2.3502307, 2.3829153, 2.2487555],
       [2.102693 , 2.477261 , 2.441666 , 2.690346 ],
       [2.0105565, 2.1723588, 2.115073 , 2.7031705],
       [2.5642896, 2.761415 , 2.9561253, 2.9251668]], dtype=float32)

In [42]:
m2.add_(1)
np1

array([[1.4406708, 1.3502306, 1.3829153, 1.2487556],
       [1.1026931, 1.4772611, 1.4416659, 1.690346 ],
       [1.0105565, 1.1723588, 1.115073 , 1.7031705],
       [1.5642896, 1.761415 , 1.9561253, 1.9251668]], dtype=float32)

In [43]:
# numpy array to Tensor when using torch.from_numpy() function but not torch.tensor() function
ta1 = torch.from_numpy(np1)
ta1

tensor([[1.4407, 1.3502, 1.3829, 1.2488],
        [1.1027, 1.4773, 1.4417, 1.6903],
        [1.0106, 1.1724, 1.1151, 1.7032],
        [1.5643, 1.7614, 1.9561, 1.9252]])

In [44]:
np1 += 1
ta1

tensor([[2.4407, 2.3502, 2.3829, 2.2488],
        [2.1027, 2.4773, 2.4417, 2.6903],
        [2.0106, 2.1724, 2.1151, 2.7032],
        [2.5643, 2.7614, 2.9561, 2.9252]])