In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np

In [3]:
# creating tensors directly
data = np.random.random((100,100))
x_data = torch.tensor(data)
x_data

tensor([[0.7598, 0.4631, 0.1341,  ..., 0.0470, 0.8023, 0.6352],
        [0.3156, 0.4405, 0.0802,  ..., 0.2267, 0.6748, 0.9082],
        [0.4126, 0.3887, 0.2969,  ..., 0.0794, 0.3039, 0.5560],
        ...,
        [0.7992, 0.9384, 0.8660,  ..., 0.8076, 0.5519, 0.5746],
        [0.6467, 0.9032, 0.3929,  ..., 0.8716, 0.4488, 0.2312],
        [0.7890, 0.6051, 0.0055,  ..., 0.2346, 0.1194, 0.1913]],
       dtype=torch.float64)

In [4]:
# creating tensors from numpy arrays 
x_np = torch.from_numpy(data)
x_np

tensor([[0.7598, 0.4631, 0.1341,  ..., 0.0470, 0.8023, 0.6352],
        [0.3156, 0.4405, 0.0802,  ..., 0.2267, 0.6748, 0.9082],
        [0.4126, 0.3887, 0.2969,  ..., 0.0794, 0.3039, 0.5560],
        ...,
        [0.7992, 0.9384, 0.8660,  ..., 0.8076, 0.5519, 0.5746],
        [0.6467, 0.9032, 0.3929,  ..., 0.8716, 0.4488, 0.2312],
        [0.7890, 0.6051, 0.0055,  ..., 0.2346, 0.1194, 0.1913]],
       dtype=torch.float64)

In [5]:
# creating tensors from other tensors
x_ones = torch.ones_like(x_np)
x_rand = torch.rand_like(x_data)
x_ones, x_rand

(tensor([[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]], dtype=torch.float64),
 tensor([[0.5976, 0.8977, 0.4748,  ..., 0.7581, 0.0924, 0.9813],
         [0.4373, 0.4155, 0.8838,  ..., 0.3931, 0.7274, 0.9537],
         [0.0933, 0.9434, 0.3893,  ..., 0.1129, 0.9062, 0.0154],
         ...,
         [0.5394, 0.5676, 0.9891,  ..., 0.4391, 0.6730, 0.6702],
         [0.1469, 0.5472, 0.7944,  ..., 0.8305, 0.2899, 0.8590],
         [0.9799, 0.6846, 0.9245,  ..., 0.3669, 0.4949, 0.7953]],
        dtype=torch.float64))

In [6]:
# creating tensors with a shape 
shape = (10,10)
s_ones = torch.ones(shape)
s_rand = torch.rand(shape)
s_zeros = torch.zeros(shape)
s_ones, s_zeros, s_rand

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.,

In [7]:
# tensor attributes
s_rand.shape, s_zeros.dtype, s_ones.device

(torch.Size([10, 10]), torch.float32, device(type='cpu'))

In [10]:
# tensor device to gpu
if torch.cuda.is_available(): s_rand = s_rand.to("cuda")
s_rand.shape, s_rand.dtype, s_rand.device

(torch.Size([10, 10]), torch.float32, device(type='cuda', index=0))

In [9]:
# tensor device back to cpu
s_rand = s_rand.to("cpu")
s_rand.shape, s_rand.dtype, s_rand.device

(torch.Size([10, 10]), torch.float32, device(type='cpu'))