In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import torch
from torch import nn

In [18]:
# Need Neural network definition for loading models from model weights or model weights plus structures

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512,10),
        )
    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

In [9]:
model = NeuralNetwork()
model

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

In [19]:
# loading models with model weights

model_weights = torch.load('./models/tutorial6_model_weights.pth')
model.load_state_dict(model_weights)
model.eval(), list(model.parameters())

(NeuralNetwork(
   (flatten): Flatten(start_dim=1, end_dim=-1)
   (linear_relu_stack): Sequential(
     (0): Linear(in_features=784, out_features=512, bias=True)
     (1): ReLU()
     (2): Linear(in_features=512, out_features=512, bias=True)
     (3): ReLU()
     (4): Linear(in_features=512, out_features=10, bias=True)
   )
 ),
 [Parameter containing:
  tensor([[-0.0067, -0.0023,  0.0232,  ...,  0.0303,  0.0175,  0.0049],
          [-0.0192, -0.0096,  0.0078,  ..., -0.0355,  0.0077, -0.0336],
          [-0.0345,  0.0078,  0.0123,  ..., -0.0093, -0.0211,  0.0016],
          ...,
          [ 0.0226, -0.0055, -0.0179,  ...,  0.0122,  0.0316, -0.0048],
          [ 0.0076, -0.0108, -0.0157,  ...,  0.0199, -0.0013, -0.0321],
          [-0.0299, -0.0155, -0.0176,  ...,  0.0089,  0.0353, -0.0346]],
         device='cuda:0', requires_grad=True),
  Parameter containing:
  tensor([ 3.6631e-02,  3.5691e-02,  4.1226e-02,  2.4847e-02, -5.9365e-03,
           1.4867e-02, -5.6825e-03,  1.6332e-02,  2.

In [21]:
# Loading model with the strucutre encoded, still needs NeuralNetwork function

model = torch.load('./models/tutorial6_model.pth')
model.eval(), list(model.parameters())

(NeuralNetwork(
   (flatten): Flatten(start_dim=1, end_dim=-1)
   (linear_relu_stack): Sequential(
     (0): Linear(in_features=784, out_features=512, bias=True)
     (1): ReLU()
     (2): Linear(in_features=512, out_features=512, bias=True)
     (3): ReLU()
     (4): Linear(in_features=512, out_features=10, bias=True)
   )
 ),
 [Parameter containing:
  tensor([[-0.0067, -0.0023,  0.0232,  ...,  0.0303,  0.0175,  0.0049],
          [-0.0192, -0.0096,  0.0078,  ..., -0.0355,  0.0077, -0.0336],
          [-0.0345,  0.0078,  0.0123,  ..., -0.0093, -0.0211,  0.0016],
          ...,
          [ 0.0226, -0.0055, -0.0179,  ...,  0.0122,  0.0316, -0.0048],
          [ 0.0076, -0.0108, -0.0157,  ...,  0.0199, -0.0013, -0.0321],
          [-0.0299, -0.0155, -0.0176,  ...,  0.0089,  0.0353, -0.0346]],
         device='cuda:0', requires_grad=True),
  Parameter containing:
  tensor([ 3.6631e-02,  3.5691e-02,  4.1226e-02,  2.4847e-02, -5.9365e-03,
           1.4867e-02, -5.6825e-03,  1.6332e-02,  2.